# Generated by Django 5.0.7 on 2024-09-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='category',
            field=models.ManyToManyField(to='categories.categories'),
        ),
    ]
