# Generated by Django 5.0.7 on 2024-09-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.CharField(default=0, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('cooking_time', models.IntegerField(default=0)),
                ('servings', models.IntegerField(blank=True, null=True)),
                ('ingredients', models.JSONField(default=list)),
            ],
        ),
    ]
