# Generated by Django 5.0.7 on 2024-09-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantry',
            name='quantity',
            field=models.CharField(max_length=20),
        ),
    ]
