# Generated by Django 5.0.7 on 2024-09-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('pantry', '0002_alter_pantry_quantity'),
        ('users', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantry',
            name='category',
            field=models.ManyToManyField(related_name='pantries', to='categories.categories'),
        ),
        migrations.AddField(
            model_name='pantry',
            name='users',
            field=models.ManyToManyField(related_name='pantries', to='users.user'),
        ),
        migrations.AlterField(
            model_name='pantry',
            name='item',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pantry',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
